// <auto-generated />
namespace StoreOwnerApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changedproductmode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedproductmode));
        
        string IMigrationMetadata.Id
        {
            get { return "201410261804279_changedproductmode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
